// Single source of the Prisma client for the whole monorepo.
// bot / web / worker all import from here — never instantiate their own.

// Note: `@prisma/client` is generated by `pnpm db:generate` after the schema's
// models exist. Until then this re-export is the intended shape.
export * from "@prisma/client";
