import { describe, it, expect } from "vitest";
import {
  themeColor,
  safeFileName,
  npcCardMarkdown,
  type NpcCard,
} from "./embeds.js";

describe("themeColor", () => {
  it("returns the theme's DM and player shades", () => {
    expect(themeColor("firelight", "DM")).toBe(0xd4a017);
    expect(themeColor("firelight", "PLAYER")).toBe(0xe8833a);
    expect(themeColor("arcane", "DM")).toBe(0x4f46e5);
  });

  it("falls back to firelight for an unknown theme", () => {
    expect(themeColor("nonsense", "DM")).toBe(themeColor("firelight", "DM"));
    expect(themeColor("", "PLAYER")).toBe(themeColor("firelight", "PLAYER"));
  });

  it("treats any non-DM role as the player shade", () => {
    expect(themeColor("firelight", "whatever")).toBe(
      themeColor("firelight", "PLAYER"),
    );
  });
});

describe("safeFileName", () => {
  it("replaces unsafe characters with underscores", () => {
    expect(safeFileName("Vesna Quill")).toBe("Vesna_Quill");
    expect(safeFileName("a/b\\c:d")).toBe("a_b_c_d");
  });

  it("keeps dots, dashes, and underscores", () => {
    expect(safeFileName("a.b-c_d")).toBe("a.b-c_d");
  });

  it("falls back to 'npc' only when the result is empty", () => {
    expect(safeFileName("")).toBe("npc");
  });
});

describe("npcCardMarkdown", () => {
  const npc: NpcCard = {
    name: "Vesna Quill",
    race: "Human",
    role: "archivist",
    appearance: "gaunt and ink-stained",
    demeanor: "clipped",
    voice: "a dry whisper",
    ties: "the Shifting Stacks",
    hook: "knows a dangerous page",
    secret: "she works for the Penumbral Court",
  };

  it("includes every field, including the DM secret", () => {
    const md = npcCardMarkdown(npc, "gnome scholar.png");
    expect(md).toContain("# Vesna Quill");
    expect(md).toContain("Human · archivist");
    expect(md).toContain("DM secret: she works for the Penumbral Court");
    expect(md).toContain("gnome scholar.png");
  });

  it("omits the portrait line when there's no match", () => {
    const md = npcCardMarkdown(npc, null);
    expect(md).toContain("_Generated by Hearth_");
    expect(md).not.toContain("Portrait:");
  });
});
