import { describe, it, expect } from "vitest";
import {
  answerEmbed,
  answerEmbeds,
  themeColor,
  safeFileName,
  npcCardMarkdown,
  type NpcCard,
} from "./embeds.js";

describe("themeColor", () => {
  it("returns the theme's DM and player shades", () => {
    expect(themeColor("firelight", "DM")).toBe(0xd4a017);
    expect(themeColor("firelight", "PLAYER")).toBe(0xe8833a);
    expect(themeColor("arcane", "DM")).toBe(0x4f46e5);
  });

  it("falls back to firelight for an unknown theme", () => {
    expect(themeColor("nonsense", "DM")).toBe(themeColor("firelight", "DM"));
    expect(themeColor("", "PLAYER")).toBe(themeColor("firelight", "PLAYER"));
  });

  it("treats any non-DM role as the player shade", () => {
    expect(themeColor("firelight", "whatever")).toBe(
      themeColor("firelight", "PLAYER"),
    );
  });
});

describe("safeFileName", () => {
  it("replaces unsafe characters with underscores", () => {
    expect(safeFileName("Vesna Quill")).toBe("Vesna_Quill");
    expect(safeFileName("a/b\\c:d")).toBe("a_b_c_d");
  });

  it("keeps dots, dashes, and underscores", () => {
    expect(safeFileName("a.b-c_d")).toBe("a.b-c_d");
  });

  it("falls back to 'npc' only when the result is empty", () => {
    expect(safeFileName("")).toBe("npc");
  });
});

describe("npcCardMarkdown", () => {
  const npc: NpcCard = {
    name: "Vesna Quill",
    race: "Human",
    role: "archivist",
    appearance: "gaunt and ink-stained",
    demeanor: "clipped",
    voice: "a dry whisper",
    ties: "the Shifting Stacks",
    hook: "knows a dangerous page",
    secret: "she works for the Penumbral Court",
  };

  it("includes every field, including the DM secret", () => {
    const md = npcCardMarkdown(npc, "gnome scholar.png");
    expect(md).toContain("# Vesna Quill");
    expect(md).toContain("Human · archivist");
    expect(md).toContain("DM secret: she works for the Penumbral Court");
    expect(md).toContain("gnome scholar.png");
  });

  it("omits the portrait line when there's no match", () => {
    const md = npcCardMarkdown(npc, null);
    expect(md).toContain("_Generated by Hearth_");
    expect(md).not.toContain("Portrait:");
  });
});

describe("answerEmbed sources", () => {
  const result = {
    answer: "An answer.",
    sources: [
      { title: "Secret Villain Plans.md", type: "DOCUMENT" },
      { title: "NPCs.md", type: "DOCUMENT" },
    ],
  };
  const viewer = (role: "DM" | "PLAYER") => ({
    campaignId: "c1",
    role,
    characterId: role === "DM" ? null : "char-1",
    partyId: role === "DM" ? null : "party-1",
  });

  it("shows the DM where an answer came from", () => {
    const embed = answerEmbed(viewer("DM"), null, "Who?", result).toJSON();
    expect(embed.footer?.text).toContain("Secret Villain Plans.md");
  });

  it("never shows a player document names — a file name can be a spoiler", () => {
    const embed = answerEmbed(
      viewer("PLAYER"),
      "Tobin",
      "Who?",
      result,
    ).toJSON();
    expect(embed.footer).toBeUndefined();
    expect(JSON.stringify(embed)).not.toContain(".md");
  });
});

describe("answerEmbeds", () => {
  const dm = {
    campaignId: "c1",
    role: "DM" as const,
    characterId: null,
    partyId: null,
  };
  const long = Array.from(
    { length: 40 },
    (_, i) => `Paragraph ${i}: ${"word ".repeat(40)}`,
  ).join("\n\n");

  it("sends a long briefing whole, across several embeds, instead of cutting it off", () => {
    const embeds = answerEmbeds(dm, null, "Tell me about the Widow", {
      answer: long,
      sources: [{ title: "NPCs.md", type: "DOCUMENT" }],
    }).map((e) => e.toJSON());
    expect(embeds.length).toBeGreaterThan(1);
    expect(embeds.every((e) => (e.description ?? "").length <= 4096)).toBe(
      true,
    );
    const joined = embeds.map((e) => e.description).join("\n\n");
    expect(joined).toContain("Paragraph 0:");
    expect(joined).toContain("Paragraph 39:");
    // Sources once, at the end.
    expect(embeds.at(-1)!.footer?.text).toContain("NPCs.md");
    expect(embeds[0]!.footer).toBeUndefined();
  });

  it("keeps a short answer in one embed", () => {
    expect(
      answerEmbeds(dm, null, "Q", { answer: "Short.", sources: [] }),
    ).toHaveLength(1);
  });
});
